environment:
  matrix:
    - nodejs_version: "stable"
    - nodejs_version: "4"
    - nodejs_version: "0.12"
    - nodejs_version: "0.10"

install:
- ps: >-
    Install-Product node $env:nodejs_version
    choco install GoogleChrome
    choco install Firefox

- cmd: >-
    npm install

build: off

test_script:
- cmd: >-
  npm test